### ISSUE TITLE
Doesn't open .JAR files

### ISSUE THREAD

**Issue by FFY00** [LPK-Matt/SkidGUI#3]
With the current code I can't open .JAR files.

**Comment by LPK-Matt** [comment]
Can you provide a series of screenshots showing what you are doing? It's working fine for me and I'm not sure how to reproduce the issue.

**Comment by FFY00** [comment]
Here: http://recordit.co/q43PWtW4NL

**Comment by LPK-Matt** [comment]
Uhhh.... That's working. Those buttons are disabled by default. In your video they are enabled. 

On a side note, not everything is completely functional. But the issue is does not exist.

**Comment by FFY00** [comment]
OK, I will see.
